# Generated by Django 4.1.13 on 2024-04-04 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='captcha_images/')),
                ('key_content', models.CharField(max_length=255)),
            ],
        ),
    ]
